import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import {sassPlugin} from "esbuild-sass-plugin";
import path from "node:path";
import * as fs from "node:fs";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = false; //(process.argv[2] === "production");

let wasmPlugin = {
	name: 'wasm',
	setup(build) {

		// Resolve ".wasm" files to a path with a namespace
		build.onResolve({filter: /\.wasm$/}, args => {
			if (args.resolveDir === '') {
				return // Ignore unresolvable paths
			}
			return {
				path: path.isAbsolute(args.path) ? args.path : path.join(args.resolveDir, args.path),
				namespace: 'wasm-binary',
			}
		})

		// Virtual modules in the "wasm-binary" namespace contain the
		// actual bytes of the WebAssembly file. This uses esbuild's
		// built-in "binary" loader instead of manually embedding the
		// binary data inside JavaScript code ourselves.
		build.onLoad({filter: /.*/, namespace: 'wasm-binary'}, async (args) => ({
			contents: await fs.promises.readFile(args.path),
			loader: 'binary',
		}))
	},
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	outdir: "dist",
	bundle: true,
	external: [
		"obsidian",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	plugins: [
		sassPlugin(),
		wasmPlugin],
	loader: {'.mp3': 'file'},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
