import typescript from '@rollup/plugin-typescript';
import {nodeResolve} from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import url from '@rollup/plugin-url';
import wasm from '@rollup/plugin-wasm';
import svelte from 'rollup-plugin-svelte';
import * as sass from 'sass';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import svelteConfig from './svelte.config.js';

const isProd = (process.env.BUILD === 'production');
const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugin's github repository
*/
`;

function sassStyles() {
  let css;

  return {
    name: 'sass-styles',
    buildStart() {
      const result = sass.compile('src/styles.scss', {style: 'compressed'});
      css = result.css;

      for (const loadedUrl of result.loadedUrls) {
        if (loadedUrl.protocol === 'file:') {
          this.addWatchFile(fileURLToPath(loadedUrl));
        }
      }
    },
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: 'styles.css',
        source: css
      });
    }
  };
}

function markdownString() {
  return {
    name: 'markdown-string',
    load(id) {
      if (!id.endsWith('.md')) {
        return null;
      }

      return `export default ${JSON.stringify(readFileSync(id, 'utf8'))};`;
    }
  };
}

function isKnownDependencyCycle(warning) {
  if (warning.code !== 'CIRCULAR_DEPENDENCY' || !warning.ids?.length) {
    return false;
  }

  const dependencyPaths = [
    '/node_modules/mathjs/',
    '/node_modules/svelte/'
  ];

  return dependencyPaths.some(dependencyPath =>
    warning.ids.every(id =>
      id.replaceAll('\\', '/').includes(dependencyPath)
    )
  );
}

export default {
  input: 'src/main.ts',
  onwarn(warning, warn) {
    if (!isKnownDependencyCycle(warning)) {
      warn(warning);
    }
  },
  output: {
    file: 'main.js',
    sourcemap: 'inline',
    sourcemapExcludeSources: isProd,
    format: 'cjs',
    exports: 'default',
    banner,
    inlineDynamicImports: true
  },
  external: ['obsidian', 'codemirror'],
  plugins: [
    // WASM plugin must come first to properly handle wasm imports
    wasm({
      sync: [
        '**/cooklang_wasm_bg.wasm'
      ],
      maxFileSize: 10000000 // 10MB limit for WASM files
    }),
    svelte({
      ...svelteConfig,
      emitCss: false,
      compilerOptions: {
        ...svelteConfig.compilerOptions,
        dev: !isProd
      }
    }),
    typescript({
      tsconfig: './tsconfig.json',
      outDir: '.',
      noEmitOnError: true,
      sourceMap: true,
      inlineSources: !isProd
    }),
    nodeResolve({
      browser: true,
      preferBuiltins: false,
      extensions: ['.js', '.ts', '.svelte']
    }),
    commonjs({
      include: ['node_modules/**', 'src/mode/**']
    }),
    markdownString(),
    sassStyles(),
    url({
      include: ['**/*.mp3'],
      limit: 100000
    })
  ]
};
